FROM python:3.10-slim

WORKDIR /app

COPY . /app/backend

RUN pip install --no-cache-dir requests sqlalchemy anthropic python-dotenv fastapi uvicorn

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000"]